apiVersion: v1
kind: Service
metadata:
  name: app-api
  namespace: app
  labels:
    app: app-api
  # To allow Prometheus to pull metrics
  #   See hereï¼šhttps://medium.com/penguin-lab/research-about-annotations-such-as-prometheus-io-scrape-6cba3121de59
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /api/metrics
    prometheus.io/port: "8080"
spec:
  ports:
    - port: 8080
  selector:
    app: app-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: app
  labels:
    app: app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
        - name: app-api
          image: app/api
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-api-config
